export const STRINGS = {
  ja: {
    dropLabel: "クリックまたはドラッグ&ドロップで動画を選択",
    dropChange: "別の動画を選択",
    generate: "字幕を生成",
    cancelGenerate: "キャンセル",
    cancelling: "キャンセル中...",
    openFolder: "出力フォルダを開く",
    sectionSelectVideo: "1. 動画を選択",
    sectionPreview: "2. プレビュー",
    sectionAction: "3. アクション",
    groupPreset: "プリセット",
    presetManage: "プリセット管理",
    presetManageTitle: "プリセット管理",
    presetSelectLabel: "編集するプリセット",
    presetSelectDeleteLabel: "削除するプリセット",
    presetSelectRestoreLabel: "復元するプリセット",
    presetNameLabel: "プリセット名",
    presetNewPlaceholder: "新規プリセット",
    presetAdd: "新規追加",
    presetEdit: "編集",
    presetAddConfirm: "追加",
    presetChangeConfirm: "変更",
    presetDelete: "削除",
    presetRestoreDefaults: "デフォルトプリセットの復元",
    presetRestoreConfirm: "復元",
    presetClose: "閉じる",
    groupBasic: "基本設定",
    groupSubtitleDesign: "字幕デザイン",
    labelLanguage: "文字起こし言語",
    autoLangOption: "自動（99言語対応）",
    labelModel: "文字起こし精度",
    labelPrompt: "話しているテーマ・キーワード",
    promptPlaceholder: "例: ワンピース、マイクラ、料理レシピ",
    labelOutputFolder: "出力先フォルダ",
    folderDefault: "動画フォルダ内の output/",
    folderSelect: "選択",
    labelOutputName: "出力ファイル名",
    labelOutputType: "出力タイプ",
    outputTypeVideo: "字幕焼き込み動画のみ",
    outputTypeSubtitle: "字幕ファイルのみ",
    outputTypeBoth: "両方",
    labelOutputFormat: "出力形式",
    labelSubtitleFormats: "字幕形式",
    labelFont: "フォント名",
    labelFontSize: "フォントサイズ",
    labelBold: "太字",
    labelHighlight: "ハイライト色",
    labelTextColor: "文字色",
    labelVertical: "縦書き",
    labelHighlightStyle: "演出スタイル",
    labelDisplayMode: "表示モード",
    labelSubtitlePosition: "字幕位置",
    positionAuto: "自動",
    positionManual: "手動",
    labelPositionX: "横位置",
    labelPositionY: "縦位置",
    styleNone: "なし",
    styleColor: "色変更",
    styleColorHold: "カラーキープ",
    styleFill: "カラオケ",
    styleDim: "フォーカス",
    styleDimHold: "フォーカスキープ",
    styleScale: "スケール",
    styleGlow: "グロー",
    displayNormal: "通常",
    displayWordPopup: "ワードポップ",
    displayWordBuild: "ワードビルド",
    displayWordBuildLeft: "ワードビルド（左固定）",
    displayStacking: "積み上げ",
    labelSimultaneousLines: "同時表示行数",
    labelPreShow: "先行表示 秒",
    labelHold: "表示保持 秒",
    labelMaxChars: "1行の最大文字数",
    stepStarting: "開始中...",
    stepAudio: "音声を抽出中...",
    stepTranscribe: "文字起こし中...",
    stepSubtitle: "字幕ファイルを生成中...",
    stepRender: "動画を書き出し中...",
    stepDone: "完了しました",
    statusSuccess: "書き出しが完了しました",
    statusCancelled: "字幕生成をキャンセルしました",
    errorPrefix: "エラー: ",
    cancelConfirmTitle: "字幕生成をキャンセルしますか？",
    cancelConfirmMessage: "現在の処理を中断します。途中まで生成されたファイルは残る場合があります。",
    cancelConfirmYes: "はい",
    cancelConfirmNo: "いいえ",
    downloadTitle: "Whisperモデルをダウンロード中...",
    downloadDesc: "しばらくお待ちください（約1.5 GB）",
    modelNotInstalled: "（未インストール）",
    highModelUnavailableOption: "高精度（低速・無料追加DL必要・約1.5GB）",
    highModelDownloadButton: "高精度モデルを無料DL",
    highModelConfirmTitle: "高精度モデルをダウンロードしますか？",
    highModelConfirmMessage:
      "追加ダウンロードは無料ですが、約1.5GBの容量が必要です。標準モデルでも、カスタム辞書登録や「話しているテーマ・キーワード」の指定で精度向上が見込めます。",
    highModelConfirmYes: "はい、無料DLする",
    highModelConfirmNo: "いいえ",
    licenses: "ライセンス",
    licensesTitle: "使用フォントのライセンス",
    licenseBadge: "Licensed under SIL Open Font License 1.1",
    licenseNote: "ライセンス本文はアプリ内 licenses/OFL_*.txt に同梱されています",
    licenseLink: "openfontlicense.org →",
    licenseClose: "閉じる",
    previewExpand: "プレビューを拡大 ↗",
    previewCollapse: "プレビューを縮小 ↙",
    previewLandscape: "横長 16:9",
    previewPortrait: "スマホ 9:16",
    groupDict: "カスタム辞書",
    dictAdd: "追加",
    dictFromPlaceholder: "音声",
    dictToPlaceholder: "表示テキスト",
    dictEmpty: "登録なし",
    dictDelete: "削除",
    labelBilingual: "バイリンガル字幕",
    labelBilingualDesc: "英語訳を同時表示（処理時間2倍）",
    stepTranslate: "翻訳中...",
    switchLang: "English",
  },
  en: {
    dropLabel: "Click or drag & drop a video",
    dropChange: "Select another video",
    generate: "Generate Subtitles",
    cancelGenerate: "Cancel",
    cancelling: "Cancelling...",
    openFolder: "Open Output Folder",
    sectionSelectVideo: "1. Select Video",
    sectionPreview: "2. Preview",
    sectionAction: "3. Action",
    groupPreset: "Presets",
    presetManage: "Manage Presets",
    presetManageTitle: "Manage Presets",
    presetSelectLabel: "Preset to edit",
    presetSelectDeleteLabel: "Preset to delete",
    presetSelectRestoreLabel: "Preset to restore",
    presetNameLabel: "Preset name",
    presetNewPlaceholder: "New preset",
    presetAdd: "Add New",
    presetEdit: "Edit",
    presetAddConfirm: "Add",
    presetChangeConfirm: "Change",
    presetDelete: "Delete",
    presetRestoreDefaults: "Restore Default Presets",
    presetRestoreConfirm: "Restore",
    presetClose: "Close",
    groupBasic: "Basic Settings",
    groupSubtitleDesign: "Subtitle Design",
    labelLanguage: "Transcription language",
    autoLangOption: "Auto (99 languages)",
    labelModel: "Transcription Quality",
    labelPrompt: "Topic / Keywords",
    promptPlaceholder: "e.g. cooking, minecraft, travel",
    labelOutputFolder: "Output Folder",
    folderDefault: "video folder/output/",
    folderSelect: "Browse",
    labelOutputName: "Output filename",
    labelOutputType: "Output type",
    outputTypeVideo: "Burned-in video only",
    outputTypeSubtitle: "Subtitle file only",
    outputTypeBoth: "Both",
    labelOutputFormat: "Output format",
    labelSubtitleFormats: "Subtitle formats",
    labelFont: "Font",
    labelFontSize: "Font Size",
    labelBold: "Bold",
    labelHighlight: "Highlight Color",
    labelTextColor: "Text Color",
    labelVertical: "Vertical",
    labelHighlightStyle: "Effect Style",
    labelDisplayMode: "Display Mode",
    labelSubtitlePosition: "Subtitle Position",
    positionAuto: "Auto",
    positionManual: "Manual",
    labelPositionX: "Horizontal",
    labelPositionY: "Vertical",
    styleNone: "None",
    styleColor: "Color",
    styleColorHold: "Color Hold",
    styleFill: "Karaoke Fill",
    styleDim: "Focus",
    styleDimHold: "Focus Hold",
    styleScale: "Scale",
    styleGlow: "Glow",
    displayNormal: "Normal",
    displayWordPopup: "Word Pop",
    displayWordBuild: "Word Build",
    displayWordBuildLeft: "Word Build (Left Fixed)",
    displayStacking: "Stacking",
    labelSimultaneousLines: "Simultaneous lines",
    labelPreShow: "Pre-show (sec)",
    labelHold: "Hold (sec)",
    labelMaxChars: "Max chars / line",
    stepStarting: "Starting...",
    stepAudio: "Extracting audio...",
    stepTranscribe: "Transcribing...",
    stepSubtitle: "Generating subtitles...",
    stepRender: "Rendering video...",
    stepDone: "Done",
    statusSuccess: "Export complete",
    statusCancelled: "Subtitle generation was cancelled",
    errorPrefix: "Error: ",
    cancelConfirmTitle: "Cancel subtitle generation?",
    cancelConfirmMessage: "The current process will stop. Partially generated files may remain.",
    cancelConfirmYes: "Yes",
    cancelConfirmNo: "No",
    downloadTitle: "Downloading Whisper model...",
    downloadDesc: "Please wait (approx. 1.5 GB)",
    modelNotInstalled: " (not installed)",
    highModelUnavailableOption: "High accuracy (slow, free extra download, approx. 1.5 GB)",
    highModelDownloadButton: "Free High Accuracy DL",
    highModelConfirmTitle: "Download the high accuracy model?",
    highModelConfirmMessage:
      "The extra download is free, but it requires about 1.5 GB. The standard model can also improve with custom dictionary entries and Topic / Keywords hints.",
    highModelConfirmYes: "Yes, download free",
    highModelConfirmNo: "No",
    licenses: "Licenses",
    licensesTitle: "Font Licenses",
    licenseBadge: "Licensed under SIL Open Font License 1.1",
    licenseNote: "License texts are bundled in licenses/OFL_*.txt",
    licenseLink: "openfontlicense.org →",
    licenseClose: "Close",
    previewExpand: "Expand Preview ↗",
    previewCollapse: "Shrink Preview ↙",
    previewLandscape: "Landscape 16:9",
    previewPortrait: "Mobile 9:16",
    groupDict: "Custom Dictionary",
    dictAdd: "Add",
    dictFromPlaceholder: "Speech",
    dictToPlaceholder: "Display text",
    dictEmpty: "No entries",
    dictDelete: "Delete",
    labelBilingual: "Bilingual Subtitles",
    labelBilingualDesc: "Show English translation (2× processing time)",
    stepTranslate: "Translating...",
    switchLang: "日本語",
  },
};

export const MODEL_LABELS = {
  "models/ggml-medium.bin":         { ja: "標準（高速）",  en: "Standard (fast)" },
  "models/ggml-large-v3-turbo.bin": { ja: "高精度（低速）", en: "High accuracy (slow)" },
};

export const PRESETS = [
  {
    id: "simple",
    label: "Simple",
    labelJa: "シンプル",
    fontName: "Noto Sans JP",
    fontWeight: 0,
    fontSize: 90,
    highlightColor: "&H00FFFFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "none",
  },
  {
    id: "viral",
    label: "Snap",
    labelJa: "スナップ",
    fontName: "GenEi Kiwami Gothic",
    fontFallbacks: ["源暎きわみゴ", "GenEi Kiwami Go", "GenEiKiwamiGo"],
    fontWeight: 0,
    fontSize: 150,
    highlightColor: "&H0000FFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "color",
    displayMode: "word_popup",
    preShowS: 0,
    holdS: 0.05,
    maxSimultaneousLines: 1,
    vertical: false,
  },
  {
    id: "capcut_bounce",
    label: "CapCut Bounce",
    labelJa: "テキスト拡大",
    fontName: "源暎ぽっぷる Black",
    fontFallbacks: ["源暎ぽっぷる", "源暎ぽっぷる Pw Black", "GenEi POPle", "GenEiPOPle"],
    fontWeight: -1,
    fontSize: 140,
    highlightColor: "&H0000FF00&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "scale",
  },
  {
    id: "mrbeast",
    label: "Impact",
    labelJa: "インパクト",
    fontName: "GenEi Kiwami Gothic",
    fontFallbacks: ["源暎きわみゴ", "GenEi Kiwami Go", "GenEiKiwamiGo"],
    fontWeight: 0,
    fontSize: 160,
    highlightColor: "&H000000FF&",
    textColor: "&H0000FFFF&",
    highlightStyle: "color",
  },
  {
    id: "netflix_focus",
    label: "Vlog",
    labelJa: "Vlog",
    fontName: "07にくまるフォント",
    fontFallbacks: ["にくまるフォント", "Nikumaru", "07NikumaruFont"],
    fontWeight: 0,
    fontSize: 110,
    highlightColor: "&H00FFFFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "dim_hold",
    maxSimultaneousLines: 2,
  },
  {
    id: "highlight",
    label: "Highlight",
    labelJa: "ハイライト",
    fontName: "Zen Kaku Gothic New",
    fontWeight: -1,
    fontSize: 120,
    highlightColor: "&H0000FFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "color_hold",
    displayMode: "normal",
    maxSimultaneousLines: 2,
    vertical: false,
  },
  {
    id: "twitch_reactive",
    label: "Neon",
    labelJa: "ネオン",
    fontName: "源暎エムゴv2 Heavy",
    fontFallbacks: ["源暎エムゴ", "源暎エムゴv2 Bold", "GenEi MGothic", "GenEiMGothic"],
    fontWeight: -1,
    fontSize: 130,
    highlightColor: "&H00FF4691&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "glow",
  },
  {
    id: "japanese_tv",
    label: "Japanese TV",
    labelJa: "バラエティTV",
    fontName: "Zen Kaku Gothic New",
    fontWeight: -1,
    fontSize: 130,
    highlightColor: "&H0000FFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "color",
  },
  {
    id: "travel_caption",
    label: "Travel Caption",
    labelJa: "旅テロップ",
    fontName: "851チカラヨワク",
    fontFallbacks: ["851ChikaraYowaku", "851 Chikara Yowaku", "851 ChikaraYowaku"],
    fontWeight: 0,
    fontSize: 120,
    highlightColor: "&H00FFFFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "none",
    displayMode: "stacking",
    maxSimultaneousLines: 2,
    vertical: true,
  },
  {
    id: "karaoke_sync",
    label: "Karaoke Sync",
    labelJa: "カラオケ",
    fontName: "Noto Sans JP",
    fontWeight: 0,
    fontSize: 120,
    highlightColor: "&H0000FFFF&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "fill",
  },
  {
    id: "podcast",
    label: "Podcast",
    labelJa: "トーク動画",
    fontName: "Montserrat",
    fontWeight: 0,
    fontSize: 100,
    highlightColor: "&H00FFFF00&",
    textColor: "&H00FFFFFF&",
    highlightStyle: "dim",
  },
];

export const FONT_LICENSES = [
  { name: "Anton",               author: "The Anton Project Authors",            license: "SIL Open Font License 1.1" },
  { name: "Montserrat",          author: "The Montserrat Project Authors",       license: "SIL Open Font License 1.1" },
  { name: "Noto Sans JP",        author: "The Noto Project Authors",             license: "SIL Open Font License 1.1" },
  { name: "Zen Kaku Gothic New", author: "The Zen Kaku Gothic Project Authors",  license: "SIL Open Font License 1.1" },
  { name: "851チカラヨワク",       author: "8:51:22 pm",                           license: "フリーフォント",            url: "https://pm85122.onamae.jp/851fontTerm.html" },
  { name: "07にくまるフォント",    author: "Kato Masashi / M+ FONTS PROJECT",      license: "M+ FONTS LICENSE" },
  { name: "源暎きわみゴ",          author: "おきねや (okoneya.jp/font)",             license: "SIL Open Font License 1.1" },
  { name: "源暎エムゴ",            author: "おきねや (okoneya.jp/font)",             license: "SIL Open Font License 1.1" },
  { name: "源暎ぽっぷる",          author: "おきねや (okoneya.jp/font)",             license: "SIL Open Font License 1.1" },
];

export const DEFAULTS = {
  fontName: "Montserrat",
  fontSize: 150,
  highlightColor: "&H0000FFFF&",
  textColor: "&H00FFFFFF&",
  preShowS: 0.75,
  holdS: 0.5,
  maxSimultaneousLines: 2,
  vertical: false,
  maxCharsPerLine: 15,
  positionMode: "auto",
  subtitleX: 50,
  subtitleY: 85,
  fontWeight: -1,
  highlightStyle: "color",
  displayMode: "normal",
  language: "ja",
  outputFormat: "mp4",
  outputType: "video",
};

export const SAMPLE_WORDS = {
  ja: ["今日は", "いい天気", "ですね"],
  en: ["Hello", "nice", "subtitle"],
};
